export enum HttpErrorsEnum {
  VALIDATION_ERRORS = 'VALIDATION_ERRORS',
  STEAM_LOGIN_OBJECT_ERROR = 'STEAM_LOGIN_OBJECT_ERROR',
  STEAM_OPENID_VERIFY_ERROR = 'STEAM_OPENID_VERIFY_ERROR',
  STEAM_DIDNT_GET_PROFILE = 'STEAM_DIDNT_GET_PROFILE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  STEAM_BOT_INTERNAL_ERROR = 'STEAM_BOT_INTERNAL_ERROR',
  USER_INV_ERROR = 'USER_INV_ERROR',
  USER_INV_EMPTY = 'USER_INV_EMPTY',
  STEAM_CANT_SEND_OFFER = 'STEAM_CANT_SEND_OFFER',
  STEAM_CANT_GET_INVETORY = 'STEAM_CANT_GET_INVETORY',
  STEAM_BOT_INVETORY_EMPTY = 'STEAM_BOT_INVETORY_EMPTY',
  STEAM_BOT_COMMYNITY_CONFIRMATION_ERROR = 'STEAM_BOT_COMMYNITY_CONFIRMATION_ERROR',
  USER_TOKEN_ERROR = 'USER_TOKEN_ERROR',
  MISSING_ACCESS_TOKEN = 'MISSING_ACCESS_TOKEN'
}
